2005-12-08  Martin Sebor  <sebor@roguewave.com>
	STDCXX-86
	* numeric (__adjacent_difference): Renamed __value to __val in order
	to avoid MSVC 8.0 error C4980: '__value': use of this keyword requires
	/clr:oldSyntax command line option.
	* _algobase.h (fill, fill_n): Ditto.
	* vector (_C_fill): Ditto. While there, also replaced const references
	to bool in function arguments with ordinary values.


git-svn-id: https://svn.apache.org/repos/asf/incubator/stdcxx/trunk@355172 13f79535-47bb-0310-9956-ffa450edef68